---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule docker tox-travis ansible testinfra
before_script: 
  - cd nmapp 
script:
  - molecule --debug test -s docker
