# -*- mode: ruby -*-

MEM_LIMIT = "512"

# set hostname

$set_config = <<-SCRIPT

timedatectl set-timezone Europe/Moscow
hostnamectl set-hostname $(hostname)
cat <<EOF > /etc/hostname
$(hostname)
EOF

# set conf repository
sed -i 's/us.archive.ubuntu.com/mirror.yandex.ru/g' /etc/apt/sources.list
sed -i 's/security.ubuntu.com/mirror.yandex.ru/g' /etc/apt/sources.list
#apt-get update

SCRIPT



Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "generic/ubuntu1804"
  config.vm.provision "shell", inline: $set_config
  config.vm.provider "libvirt" do |vb|
        vb.memory = MEM_LIMIT
  end

  (4..5).each do |n|
    config.vm.define "sql#{n}" do |c|
        c.vm.hostname = "sql#{n}"
        c.vm.network "private_network", ip: "192.168.123.1#{n}"
    end
  end

end
