---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: instance
    box: generic/ubuntu1804
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      ssh_args: -C -o ControlMaster=auto -o ControlPersist=60s
      control_path: /dev/shm/cp%%h-%%p-%%r
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
